name: Actions Workflow

on: [push]

jobs:
  run-gitgub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run:
          pwd
          ls -a
      - name: Simple JS Action
        id: greet